/**
 * piClient.js — the only frontend module that touches window.Pi.
 * Prerequisite: index.html loads https://sdk.minepi.com/pi-sdk.js
 */

const API = import.meta.env.VITE_API_URL || 'https://taskverse-pi-backend.onrender.com';
let sessionToken = null;

export const getSessionToken = () => sessionToken;

async function api(path, body, method) {
  const res = await fetch(`${API}${path}`, {
    method: method || (body ? 'POST' : 'GET'),
    headers: {
      'Content-Type': 'application/json',
      'Bypass-Tunnel-Reminder': 'true',
      'ngrok-skip-browser-warning': 'true',
      ...(sessionToken ? { Authorization: `Bearer ${sessionToken}` } : {}),
    },
    body: body ? JSON.stringify(body) : undefined,
  });
  const data = await res.json();
  if (!res.ok) {
    const err = new Error(data.error || `Request failed (${res.status})`);
    err.status = res.status;
    err.reasons = data.reasons;
    throw err;
  }
  return data;
}

// For file-download endpoints (CSV exports) — a plain <a href> can't attach
// the Bearer auth header, so this fetches with auth like api() does, but
// reads the response as a blob and triggers the save-as dialog itself
// instead of parsing JSON.
async function downloadFile(path, fallbackFilename) {
  const res = await fetch(`${API}${path}`, {
    headers: {
      'Bypass-Tunnel-Reminder': 'true',
      'ngrok-skip-browser-warning': 'true',
      ...(sessionToken ? { Authorization: `Bearer ${sessionToken}` } : {}),
    },
  });
  if (!res.ok) {
    let msg = `Export failed (${res.status})`;
    try { msg = (await res.json()).error || msg; } catch { /* non-JSON error body */ }
    throw new Error(msg);
  }
  const disposition = res.headers.get('Content-Disposition') || '';
  const match = disposition.match(/filename="([^"]+)"/);
  const filename = match ? match[1] : fallbackFilename;
  const blob = await res.blob();
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = filename;
  document.body.appendChild(a); a.click(); document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Renders a shareable payment receipt as a PNG and triggers a download —
 * hand-drawn on a <canvas>, no charting/image library needed. Used for both
 * worker payouts and task-funding receipts (kind differs, layout doesn't).
 */
export function downloadReceiptImage({ kind, title, amountPi, refId, status, date }) {
  const w = 640, h = 760;
  const canvas = document.createElement('canvas');
  canvas.width = w; canvas.height = h;
  const ctx = canvas.getContext('2d');

  // Card background
  ctx.fillStyle = '#f4f6fb';
  ctx.fillRect(0, 0, w, h);
  ctx.fillStyle = '#ffffff';
  const pad = 32;
  roundRect(ctx, pad, pad, w - pad * 2, h - pad * 2, 20);
  ctx.fill();

  // Header band
  ctx.save();
  roundRectTop(ctx, pad, pad, w - pad * 2, 130, 20);
  const grad = ctx.createLinearGradient(pad, pad, w - pad, pad + 130);
  grad.addColorStop(0, '#059669'); grad.addColorStop(1, '#047857');
  ctx.fillStyle = grad;
  ctx.fill();
  ctx.restore();

  // Logo mark (small rounded square + checkmark, matches Logo.jsx)
  ctx.fillStyle = '#0F172A';
  roundRect(ctx, pad + 28, pad + 28, 56, 56, 14);
  ctx.fill();
  ctx.strokeStyle = '#059669';
  ctx.lineWidth = 6;
  ctx.lineCap = 'round'; ctx.lineJoin = 'round';
  ctx.beginPath();
  ctx.moveTo(pad + 44, pad + 58); ctx.lineTo(pad + 53, pad + 68); ctx.lineTo(pad + 72, pad + 44);
  ctx.stroke();

  ctx.fillStyle = '#ffffff';
  ctx.textBaseline = 'alphabetic';
  ctx.font = '700 22px system-ui, sans-serif';
  ctx.fillText('TaskVerse Earn', pad + 98, pad + 55);
  ctx.font = '600 14px system-ui, sans-serif';
  ctx.globalAlpha = 0.9;
  ctx.fillText(kind === 'payout' ? 'Payout Receipt' : 'Task Funding Receipt', pad + 98, pad + 78);
  ctx.globalAlpha = 1;

  // Body
  let y = pad + 130 + 56;
  ctx.fillStyle = '#a0aec0';
  ctx.font = '700 12px system-ui, sans-serif';
  ctx.fillText('AMOUNT', pad + 32, y);
  y += 40;
  ctx.fillStyle = '#1a202c';
  ctx.font = '800 40px system-ui, sans-serif';
  ctx.fillText(`${amountPi} π`, pad + 32, y);

  y += 52;
  const row = (label, value, mono) => {
    ctx.fillStyle = '#a0aec0';
    ctx.font = '700 11px system-ui, sans-serif';
    ctx.fillText(label, pad + 32, y);
    ctx.fillStyle = '#2d3748';
    ctx.font = mono ? '600 15px monospace' : '600 15px system-ui, sans-serif';
    ctx.fillText(String(value), pad + 32, y + 20);
    y += 56;
  };
  row('DESCRIPTION', title);
  row('REFERENCE', refId || '—', true);
  row('STATUS', status);
  row('DATE', date);

  // Footer
  ctx.fillStyle = '#a0aec0';
  ctx.font = '500 11px system-ui, sans-serif';
  ctx.fillText('Generated by TaskVerse Earn — keep this for your records.', pad + 32, h - pad - 20);

  canvas.toBlob((blob) => {
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url; a.download = `taskverse-receipt-${refId || 'receipt'}.png`;
    document.body.appendChild(a); a.click(); document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }, 'image/png');
}

function roundRect(ctx, x, y, width, height, r) {
  ctx.beginPath();
  ctx.moveTo(x + r, y);
  ctx.arcTo(x + width, y, x + width, y + height, r);
  ctx.arcTo(x + width, y + height, x, y + height, r);
  ctx.arcTo(x, y + height, x, y, r);
  ctx.arcTo(x, y, x + width, y, r);
  ctx.closePath();
}
function roundRectTop(ctx, x, y, width, height, r) {
  ctx.beginPath();
  ctx.moveTo(x + r, y);
  ctx.arcTo(x + width, y, x + width, y + height, r);
  ctx.lineTo(x + width, y + height);
  ctx.lineTo(x, y + height);
  ctx.arcTo(x, y, x + width, y, r);
  ctx.closePath();
}

export function initPi() {
  if (!window.Pi) throw new Error('Pi SDK not loaded — open this app inside the Pi Browser.');
  window.Pi.init({ version: '2.0', sandbox: import.meta.env.VITE_PI_SANDBOX === 'true' });
}
/**
 * Open an external (non-TaskVerse) URL, e.g. a task's posted link.
 * Inside Pi Browser, app content is rendered in an iframe, so a plain
 * anchor with target=_blank can't reliably hand off to native apps via Android
 * App Links / iOS Universal Links - it can fall through to a generic
 * "open in store" resolution instead. Pi.openUrlInSystemBrowser() routes
 * the URL through the OS system browser, where App Link handoff works
 * normally (e.g. https://x.com/... opens directly in the X app).
 * Falls back to window.open for non-Pi-Browser contexts (e.g. local dev)
 * or older Pi Browser versions that don't support this SDK method.
 */
export async function openExternalLink(url) {
  if (window.Pi && typeof window.Pi.openUrlInSystemBrowser === 'function') {
    try {
      await window.Pi.openUrlInSystemBrowser(url);
      return;
    } catch (err) {
      console.warn('Pi.openUrlInSystemBrowser failed, falling back:', err?.message || err);
    }
  }
  window.open(url, '_blank', 'noopener,noreferrer');
}
export async function authenticateWithPi() {
  initPi();
  const auth = await window.Pi.authenticate(
    ['username', 'payments', 'wallet_address'],
    handleIncompletePayment
  );
  const { sessionToken: token, user } = await api('/api/auth/verify', {
    accessToken: auth.accessToken,
  });
  sessionToken = token;
  return user;
}

/**
 * Hand a stranded Pi payment back to our server so it can be completed (if it
 * actually went through on-chain) or cancelled (if it didn't).
 *
 * Pi refuses to create a NEW payment while an incomplete one exists for that
 * user. So if this isn't cleared, every retry fails — Pi's API returns
 * `payment_not_found` (HTTP 404) and the user is stuck permanently, with no way
 * to know that the fix is "clear browser data and log in again".
 *
 * This must therefore be passed to BOTH authenticate() and createPayment().
 * It was previously only on authenticate(), which is why a real user hit a
 * permanent wall on 2026-07-12.
 */
function handleIncompletePayment(payment) {
  return api('/api/payments/incomplete', { payment }).catch((e) => {
    console.error('Failed to clear incomplete payment:', e);
  });
}

export function payForTaskFunding({ taskId, amountToPay, title }) {
  return new Promise((resolve, reject) => {
    window.Pi.createPayment(
      { amount: amountToPay, memo: `TaskVerse campaign: ${title}`.slice(0, 100), metadata: { taskId } },
      {
        onReadyForServerApproval: (paymentId) =>
          api('/api/payments/approve', { paymentId, taskId }).catch(reject),
        onReadyForServerCompletion: (paymentId, txid) =>
          api('/api/payments/complete', { paymentId, txid }).then(resolve).catch(reject),
        // Clear a stranded payment from a previous attempt so this one can
        // proceed, instead of Pi blocking every retry forever.
        onIncompletePaymentFound: handleIncompletePayment,
        onCancel: () => reject(new Error('Payment cancelled')),
        onError: (error) => reject(explainPaymentError(error)),
      }
    );
  });
}

/**
 * Turn Pi's raw payment errors into something a user can act on.
 * "Request failed with status code 404" tells them nothing; the real meaning is
 * usually "you have a stranded payment from a previous attempt".
 */
function explainPaymentError(error) {
  const msg = String(error?.message || error || '');
  const body = JSON.stringify(error?.response?.data || {});
  if (/payment_not_found|status code 404/i.test(msg + body)) {
    return new Error(
      'That payment could not be completed — you may have an unfinished payment from a previous attempt. ' +
      'Please close the app, reopen it, and try again. If it keeps failing, sign out and sign back in.'
    );
  }
  if (/insufficient|balance/i.test(msg + body)) {
    return new Error('Not enough Pi in your wallet to cover this payment.');
  }
  return error instanceof Error ? error : new Error(msg || 'Payment failed');
}

/* ── Worker API ── */
export const createTask = (payload) => api('/api/tasks', payload);
export const fetchTasks = () => api('/api/tasks');
export const fetchMe = () => api('/api/me');
export const setMyCountry = (country) => api('/api/me/country', { country }, 'PATCH');
export const submitProof = (id, p) => api(`/api/tasks/${id}/submissions`, p);
export const fetchPayoutHistory= () => api('/api/me/history');
export const fetchLeaderboard = (period = 'week') => api(`/api/leaderboard?period=${period}`);
export const submitDisputeStatement = (id, statement) =>
  api(`/api/me/disputes/${id}/statement`, { statement });

/* ── Admin API ── */
export const fetchAdminQueue = () => api('/api/admin/queue');
export const approveSubmission= (id) => api(`/api/admin/submissions/${id}/approve`, {});
export const bulkApproveSubmissions = (ids) => api('/api/admin/queue/bulk-approve', { ids });
export const rejectSubmission = (id) => api(`/api/admin/submissions/${id}/reject`, {});
export const fetchDisputes = () => api('/api/admin/disputes');
export const resolveDispute = (id, d, note='')=> api(`/api/admin/disputes/${id}/resolve`, { decision: d, note });
export const fetchRevenue = () => api('/api/admin/revenue');
/** Create a sponsored task (goes live instantly, no Pi payment) */
export const createAdminTask = (payload) => api('/api/admin/tasks', payload);
/** Scan and complete any pending A2U payouts whose txid is now available */
export const reconcilePayouts = () => api('/api/admin/reconcile', {});
/** Cancel tasks that have been stuck in awaiting_funding longer than hoursOld (default 24) */
export const cancelStaleFunding = (hoursOld = 24) => api('/api/admin/cancel-stale-funding', { hoursOld });

// Support: read-only payment lookup + payout wallet overview
export const fetchWorkerPaymentLookup = (q) => api(`/api/admin/worker-payment-lookup?q=${encodeURIComponent(q)}`);
export const fetchWalletOverview = () => api('/api/admin/wallet-overview');

/**
 * Flush backlogged A2U payouts. Fail-safe by design:
 *  - {}                      → dry-run preview, pays nothing
 *  - { submissionId }        → pays exactly that one submission
 *  - { limit: N }            → pays at most N from the unpaid queue
 */
export const reconcileA2U = (opts = {}) => api('/api/admin/reconcile-a2u', opts);
export const fetchUnpayableSubmissions = () => api('/api/admin/unpayable-submissions');
export const reconcileConsolidated = (opts = {}) => api('/api/admin/reconcile-consolidated', opts);

/* ── Avatars ──
 * Pictures are resized + compressed in the browser BEFORE upload (see
 * resizeImageToDataUrl below), so what reaches the server is a small
 * JPEG data URL rather than a multi-megabyte camera photo.
 */
export const uploadAvatar = (avatar) => api('/api/me/avatar', { avatar }, 'PUT');
export const deleteAvatar = () => api('/api/me/avatar', undefined, 'DELETE');
export const fetchAvatar = (piUid) => api(`/api/avatar/${encodeURIComponent(piUid)}`);
export const adminRemoveAvatar = (piUid, unblock = false) =>
  api('/api/admin/avatar-remove', { piUid, unblock });

/**
 * Read a File, downscale it to fit `max`x`max`, centre-crop to a square,
 * and return a compressed JPEG data URL.
 * This is what keeps avatars ~30-50KB instead of several megabytes.
 */
export function resizeImageToDataUrl(file, max = 256, quality = 0.82) {
  return new Promise((resolve, reject) => {
    if (!file || !file.type || !file.type.startsWith('image/')) {
      return reject(new Error('Please choose an image file.'));
    }
    const reader = new FileReader();
    reader.onerror = () => reject(new Error('Could not read that file.'));
    reader.onload = () => {
      const img = new Image();
      img.onerror = () => reject(new Error('That file is not a valid image.'));
      img.onload = () => {
        try {
          // Centre-crop to a square so avatars are never stretched.
          const side = Math.min(img.width, img.height);
          const sx = (img.width - side) / 2;
          const sy = (img.height - side) / 2;

          const canvas = document.createElement('canvas');
          canvas.width = max;
          canvas.height = max;
          const ctx = canvas.getContext('2d');
          ctx.drawImage(img, sx, sy, side, side, 0, 0, max, max);

          // JPEG keeps it small. (No SVG/PNG-with-alpha needed for avatars.)
          resolve(canvas.toDataURL('image/jpeg', quality));
        } catch (e) {
          reject(new Error('Could not process that image.'));
        }
      };
      img.src = reader.result;
    };
    reader.readAsDataURL(file);
  });
}

/**
 * Like resizeImageToDataUrl, but for proof screenshots rather than avatars:
 * fits within max dimensions preserving aspect ratio (no crop — the whole
 * frame matters for proof, unlike an avatar), and allows a bit more size
 * since detail needs to stay legible.
 */
export function resizeProofImageToDataUrl(file, maxDim = 1280, quality = 0.75) {
  return new Promise((resolve, reject) => {
    if (!file || !file.type || !file.type.startsWith('image/')) {
      return reject(new Error('Please choose an image file.'));
    }
    const reader = new FileReader();
    reader.onerror = () => reject(new Error('Could not read that file.'));
    reader.onload = () => {
      const img = new Image();
      img.onerror = () => reject(new Error('That file is not a valid image.'));
      img.onload = () => {
        try {
          const scale = Math.min(1, maxDim / Math.max(img.width, img.height));
          const w = Math.round(img.width * scale);
          const h = Math.round(img.height * scale);
          const canvas = document.createElement('canvas');
          canvas.width = w; canvas.height = h;
          const ctx = canvas.getContext('2d');
          ctx.drawImage(img, 0, 0, w, h);
          resolve(canvas.toDataURL('image/jpeg', quality));
        } catch (e) {
          reject(new Error('Could not process that image.'));
        }
      };
      img.src = reader.result;
    };
    reader.readAsDataURL(file);
  });
}

/* ── Announcements ── */
export const fetchAnnouncement = () => api('/api/announcement');
export const dismissAnnouncement = (id) => api(`/api/announcement/${id}/dismiss`, {});
export const fetchAdminAnnouncements = () => api('/api/admin/announcements');
export const createAnnouncement = (payload) => api('/api/admin/announcements', payload);
export const setAnnouncementActive = (id, active) =>
  api(`/api/admin/announcements/${id}`, { active }, 'PATCH');
export const deleteAnnouncement = (id) =>
  api(`/api/admin/announcements/${id}`, undefined, 'DELETE');

/* ── Banners (promo carousel, e.g. cross-promoting Zappi NG) ── */
export const fetchBanners = () => api('/api/banners');
export const fetchAdminBanners = () => api('/api/admin/banners');
export const createBanner = (payload) => api('/api/admin/banners', payload);
export const updateBanner = (id, patch) => api(`/api/admin/banners/${id}`, patch, 'PATCH');
export const deleteBanner = (id) => api(`/api/admin/banners/${id}`, undefined, 'DELETE');

/* ── Feature flags (emergency brake + maintenance mode) ── */
export const fetchFlags = () => api('/api/flags');
export const fetchAdminFlags = () => api('/api/admin/flags');
export const createFlag = (key) => api('/api/admin/flags', { key });
export const setFlagEnabled = (key, enabled) =>
  api(`/api/admin/flags/${encodeURIComponent(key)}`, { enabled }, 'PATCH');
export const deleteFlag = (key) =>
  api(`/api/admin/flags/${encodeURIComponent(key)}`, undefined, 'DELETE');

/* ── Platform settings (fee rate, reward/slot limits, auto-approve thresholds) ── */
export const fetchSettings = () => api('/api/settings');
export const fetchAdminSettings = () => api('/api/admin/settings');
export const updateSettings = (patch) => api('/api/admin/settings', patch, 'PATCH');

/* ── Admin: user list & search ── */
export const fetchAdminUsers = (q, page = 1, limit = 20) => {
  const params = new URLSearchParams({ page: String(page), limit: String(limit) });
  if (q) params.set('q', q);
  return api(`/api/admin/users?${params.toString()}`);
};
export const setUserBanned = (id, banned) => api(`/api/admin/users/${id}/ban`, { banned }, 'PATCH');
export const exportAdminUsersCsv = (q) => {
  const params = new URLSearchParams();
  if (q) params.set('q', q);
  return downloadFile(`/api/admin/users/export.csv?${params.toString()}`, 'taskverse-users.csv');
};

/* ── Admin: transactions (all Payment records, refId lookup) ── */
export const fetchAdminTransactions = (params = {}) => {
  const q = new URLSearchParams();
  Object.entries(params).forEach(([k, v]) => { if (v !== undefined && v !== null && v !== '') q.set(k, v); });
  return api(`/api/admin/transactions?${q.toString()}`);
};
export const exportAdminTransactionsCsv = (params = {}) => {
  const q = new URLSearchParams();
  Object.entries(params).forEach(([k, v]) => { if (v !== undefined && v !== null && v !== '') q.set(k, v); });
  return downloadFile(`/api/admin/transactions/export.csv?${q.toString()}`, 'taskverse-transactions.csv');
};

/* ── Support tickets (user-facing) ── */
/* ── In-app notification feed ── */
/* ── Referrals ── */
export const fetchMyReferral = () => api('/api/me/referral');
export const submitReferralCode = (code) => api('/api/me/referral', { code });
export const fetchAdminReferrals = (params = {}) => {
  const q = new URLSearchParams();
  Object.entries(params).forEach(([k, v]) => { if (v !== undefined && v !== null && v !== '') q.set(k, v); });
  return api(`/api/admin/referrals?${q.toString()}`);
};
export const retryReferralPayout = (id) => api(`/api/admin/referrals/${id}/retry`, {});

export const fetchNotifications = () => api('/api/notifications');
export const markNotificationRead = (id) => api(`/api/notifications/${id}/read`, {});
export const markAllNotificationsRead = () => api('/api/notifications/read-all', {});

export const fetchMyTickets = () => api('/api/support/tickets');
export const createTicket = (payload) => api('/api/support/tickets', payload);
export const fetchMyTicket = (id) => api(`/api/support/tickets/${id}`);
export const replyToTicket = (id, message) => api(`/api/support/tickets/${id}/reply`, { message });

/* ── Support tickets (admin) ── */
export const fetchAdminTickets = (params = {}) => {
  const q = new URLSearchParams();
  Object.entries(params).forEach(([k, v]) => { if (v !== undefined && v !== null && v !== '') q.set(k, v); });
  return api(`/api/admin/support/tickets?${q.toString()}`);
};
export const fetchAdminTicket = (id) => api(`/api/admin/support/tickets/${id}`);
export const replyToTicketAsAdmin = (id, message) => api(`/api/admin/support/tickets/${id}/reply`, { message });
export const setTicketStatus = (id, status) => api(`/api/admin/support/tickets/${id}`, { status }, 'PATCH');
export const fetchAdminSupportUnreadCount = () => api('/api/admin/support/unread-count');

/* ── Admin: overview stats ── */
export const fetchAdminStats = () => api('/api/admin/stats');

/* ── Admin: audit log ── */
export const fetchAdminAuditLog = (params = {}) => {
  const q = new URLSearchParams();
  Object.entries(params).forEach(([k, v]) => { if (v !== undefined && v !== null && v !== '') q.set(k, v); });
  return api(`/api/admin/audit-log?${q.toString()}`);
};

/**
 * Like resizeImageToDataUrl, but fits/crops to a wide banner aspect ratio
 * (16:7 by default) instead of a square, and keeps a slightly larger JPEG
 * since these are full-width promo graphics rather than small avatars.
 */
export function resizeBannerImageToDataUrl(file, width = 960, height = 420, quality = 0.82) {
  return new Promise((resolve, reject) => {
    if (!file || !file.type || !file.type.startsWith('image/')) {
      return reject(new Error('Please choose an image file.'));
    }
    const reader = new FileReader();
    reader.onerror = () => reject(new Error('Could not read that file.'));
    reader.onload = () => {
      const img = new Image();
      img.onerror = () => reject(new Error('That file is not a valid image.'));
      img.onload = () => {
        try {
          // Cover-fit: crop to the target aspect ratio, then scale to fill.
          const targetRatio = width / height;
          const srcRatio = img.width / img.height;
          let sx, sy, sw, sh;
          if (srcRatio > targetRatio) {
            sh = img.height; sw = sh * targetRatio;
            sx = (img.width - sw) / 2; sy = 0;
          } else {
            sw = img.width; sh = sw / targetRatio;
            sx = 0; sy = (img.height - sh) / 2;
          }
          const canvas = document.createElement('canvas');
          canvas.width = width; canvas.height = height;
          const ctx = canvas.getContext('2d');
          ctx.drawImage(img, sx, sy, sw, sh, 0, 0, width, height);
          resolve(canvas.toDataURL('image/jpeg', quality));
        } catch (e) {
          reject(new Error('Could not process that image.'));
        }
      };
      img.src = reader.result;
    };
    reader.readAsDataURL(file);
  });
}

/* ── Push notifications ──────────────────────────────────────────
   Standard Web Push. Whether this actually works depends on the browser/
   WebView — every function here checks support first and fails quietly
   (resolves false / does nothing) rather than throwing, so a device that
   doesn't support it just never sees the toggle succeed, instead of
   breaking the rest of the app. */

export function isPushSupported() {
  return typeof window !== 'undefined' && 'serviceWorker' in navigator && 'PushManager' in window;
}

function urlBase64ToUint8Array(base64String) {
  const padding = '='.repeat((4 - (base64String.length % 4)) % 4);
  const base64 = (base64String + padding).replace(/-/g, '+').replace(/_/g, '/');
  const raw = atob(base64);
  return Uint8Array.from([...raw].map((c) => c.charCodeAt(0)));
}

// Current subscription state for this device, or null if unsupported/not subscribed.
export async function getPushSubscription() {
  if (!isPushSupported()) return null;
  try {
    const reg = await navigator.serviceWorker.getRegistration('/sw.js');
    if (!reg) return null;
    return await reg.pushManager.getSubscription();
  } catch { return null; }
}

// Registers the service worker (idempotent), asks for permission, subscribes,
// and saves the subscription server-side. Returns true on success.
export async function enablePushNotifications() {
  if (!isPushSupported()) throw new Error('Push notifications are not supported in this browser.');
  const { enabled, publicKey } = await api('/api/push/vapid-public-key');
  if (!enabled || !publicKey) throw new Error('Push notifications are not set up on the server yet.');

  const permission = await Notification.requestPermission();
  if (permission !== 'granted') throw new Error('Notification permission was not granted.');

  const reg = await navigator.serviceWorker.register('/sw.js');
  await navigator.serviceWorker.ready;
  let sub = await reg.pushManager.getSubscription();
  if (!sub) {
    sub = await reg.pushManager.subscribe({
      userVisibleOnly: true,
      applicationServerKey: urlBase64ToUint8Array(publicKey),
    });
  }
  const json = sub.toJSON();
  await api('/api/push/subscribe', { endpoint: json.endpoint, keys: json.keys });
  return true;
}

export async function disablePushNotifications() {
  const sub = await getPushSubscription();
  if (!sub) return;
  const endpoint = sub.endpoint;
  try { await sub.unsubscribe(); } catch { /* best-effort */ }
  try { await api('/api/push/unsubscribe', { endpoint }); } catch { /* best-effort */ }
}
